### ISSUE TITLE
Add clean method

### ISSUE THREAD

**Issue by evamaxfield** [AllenCellModeling/datastep#2]
## Use Case
*Please provide a use case to help us understand your request in context*
So that we don't have a corrupted local environment, providing a clean method on each step to remove local temp files would be great.

## Solution
*Please describe your ideal solution*
Implement `clean` in the `Step` base class.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by donovanr** [comment]
will fix #21

**Comment by donovanr** [comment]
added in 55df6b82401e25e8e3fce9a719d0bd3a93f4aab7
