### ISSUE TITLE
Make @task decorator work with run

### ISSUE THREAD

**Issue by evamaxfield** [AllenCellModeling/datastep#33]
## Use Case
*Please provide a use case to help us understand your request in context*
To allow prefect flows to actually work with our step module, we need to add the `@task` decorator to the `run` function. However not sure how to handle multiple decorators / which order they should go in.

**Comment by donovanr** [comment]
take at look at the `feature/inherit_from_task` branch.

the following works:
```
from prefect import Flow
from python_workflow import steps

raw = steps.Raw()
with Flow("My first flow!") as flow:
    raw_data = raw(N=4)
flow.run()
```

**Comment by donovanr** [comment]
see #43 — tests are passing?

**Comment by donovanr** [comment]
to clarify and move over a thought from slack:

this change is predicated on the idea that we don't actually need `run` to be an abstract method.  we just have `Step` inherit from `Task`, and let the user fill in a non-pass run function in their steps if the actually want to... run anything.

also, the prefect docs seem to imply that prefect Tasks are somehow required to have a run method implemented anyway, but i'm less clear about that.

**Comment by evamaxfield** [comment]
Working on #43:

I believe the potential solution is to include a `distributed` kwarg to the `Step` class that when `True` initializes the `project_local_staging_dir` and `step_local_staging_dir` to a specific path to some shared storage.

So during init you could do:
```python
raw = steps.Raw()
```

which will result in `raw.project_local_staging_dir` as `{cwd}/local_staging/`

But if you did:
```python
raw = steps.Raw(distributed=True)
```

`raw.project_local_staging_dir` gets set as `{some_config_path}/local_staging/`

**Comment by evamaxfield** [comment]
The config option imo, should be `distributed_storage_directory`.
