### ISSUE TITLE
local_staging/all gets created when running mti_mnist all run

### ISSUE THREAD

**Issue by donovanr** [AllenCellModeling/datastep#4]

**Comment by donovanr** [comment]
to be fair i made all a step class so it's... not a bug?  something to think about re how "all" gets run though -- maybe prefect will take care of this.

**Comment by evamaxfield** [comment]
> Something to think about re how "all" gets run though -- maybe prefect will take care of this.

Yea I thought a bit about this today. I think the cookiecutter cli for individual modules and all not in v0.1.0 release but soon after should include options to build and tear down the dask + prefect cluster and the bin script should handle all as a specific keyword.

**Comment by donovanr** [comment]
yep
