### ISSUE TITLE
Add kwarg to `run` which is "--check-strict" or "production" or similar

### ISSUE THREAD

**Issue by evamaxfield** [AllenCellModeling/datastep#9]
## Use Case
*Please provide a use case to help us understand your request in context*
Make sure that prior to running this step, that the user has the most up-to-date and valid upstream depend data.

**Comment by evamaxfield** [comment]
@donovanr I am realizing the drastic hole in the current implementation is just that if someone switches from branch to branch but doesn't clean the data and then pushes they can overwrite data/master.

I think we can get around this by creating a `.data_sync_lock` file in the `step_local_staging` that just contains a dictionary with which git commit created the data. If it isn't the current master head commit we reject it.

contents of `.data_sync_lock`:
```json
{
    "branch": "master",
    "sha": "123456..."
}
```

On this implementation I think we should add more to the `run` wrapper. Instead of just `log_run_params` it also should save the manifest for the user in the proper location and save this file imo

**Comment by evamaxfield** [comment]
Really just check this info prior to _any_ push, not just to master

**Comment by donovanr** [comment]
yeah

**Comment by donovanr** [comment]
kwargs etc to run seem hard, since users will be messing with that method definition. but having a sync check in push seems like a good idea.

**Comment by donovanr** [comment]
maybe a kwarg in the step ABC like `clean=True` that cleans the step before running?

**Comment by donovanr** [comment]
the step ABC `__init__`, sorry

**Comment by donovanr** [comment]
closed by `clean_before_run` in #30
